project:
  type: website

website:
  title: "ALA Science Impact"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: highlights.qmd
        text: Highlighted papers
      - href: research-test/research.qmd
        text: Research

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

