---
title: "paperthumbnails"
author: "Olivia"
date: "2023-03-28"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(ggplot2)
library(magick)
library(cowplot)
```


```{r}
text_size <- 30

p <- ggplot() + 
  annotate("text", 
           x=0.5, 
           y=0.5,
           size = text_size,
           label = stringr::str_wrap("the quick fox jumps over the lazy dog", text_size*0.5)) + 
  geom_rect(aes(xmin = 0.5, xmax = 1, ymin = 0.1, ymax = 0.11),
           fill = "#E06E53",
           color = "NA") +
  scale_y_continuous(limits = c(0,1)) +
  scale_x_continuous(limits = c(0, 1)) +
theme(panel.border = element_blank(),
       panel.background = element_rect(fill = "#FFC557", color = NA),
       plot.background = element_rect(fill = "#FFC557"), #remove white space from x/y region
       panel.grid = element_blank(), #remove labels, ticks etc. 
       axis.text = element_blank(),
       axis.ticks = element_blank(),
       axis.title = element_blank(),
       plot.margin = margin(0, 0, 0, 0, "cm")) #remove white space from right and top borders 
p
```

```{r}
ggsave(file = "test.png")
```








